addSbtPlugin("com.eed3si9n"    % "sbt-buildinfo"       % "0.7.0")
addSbtPlugin("com.eed3si9n"    % "sbt-assembly"        % "0.14.5")
addSbtPlugin("io.get-coursier" % "sbt-coursier"        % "1.0.0-RC12")
addSbtPlugin("org.wartremover" % "sbt-wartremover"     % "2.2.1")
addSbtPlugin("org.xerial.sbt"  % "sbt-pack"            % "0.9.1")
addSbtPlugin("ch.epfl.scala"   % "sbt-release-early"   % "2.0.0")
